In [53]:
import numpy as np
import pandas as pd

In [48]:
data = pd.read_csv('data.csv')

In [ ]:
df = pd.DataFrame(data,columns=columns)

In [7]:
df

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [8]:
df.describe()

,Year,Engine HP,Engine Cylinders,Number of Doors,highway MPG,city mpg,Popularity,MSRP
count,11914.000000,11845.00000,11884.000000,11908.000000,11914.000000,11914.000000,11914.000000,1.191400e+04
mean,2010.384338,249.38607,5.628829,3.436093,26.637485,19.733255,1554.911197,4.059474e+04
std,7.579740,109.19187,1.780559,0.881315,8.863001,8.987798,1441.855347,6.010910e+04
min,1990.000000,55.00000,0.000000,2.000000,12.000000,7.000000,2.000000,2.000000e+03
25%,2007.000000,170.00000,4.000000,2.000000,22.000000,16.000000,549.000000,2.100000e+04
50%,2015.000000,227.00000,6.000000,4.000000,26.000000,18.000000,1385.000000,2.999500e+04
75%,2016.000000,300.00000,6.000000,4.000000,30.000000,22.000000,2009.000000,4.223125e+04
max,2017.000000,1001.00000,16.000000,4.000000,354.000000,137.000000,5657.000000,2.065902e+06

In [41]:
df.loc[:,"Make"]

0            BMW
1            BMW
2            BMW
3            BMW
4            BMW
          ...
11909      Acura
11910      Acura
11911      Acura
11912      Acura
11913    Lincoln
Name: Make, Length: 11914, dtype: object

In [56]:
df.loc[:,"Make"]

0            BMW
1            BMW
2            BMW
3            BMW
4            BMW
          ...
11909      Acura
11910      Acura
11911      Acura
11912      Acura
11913    Lincoln
Name: Make, Length: 11914, dtype: object

In [58]:
df.groupby(["Make"]).first()

,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
Make,,,,,,,,,,,,,,,
Acura,CL,2001,premium unleaded (required),225.0,6.0,AUTOMATIC,front wheel drive,2.0,Luxury,Midsize,Coupe,27,17,204,29980
Alfa Romeo,4C,2015,premium unleaded (required),237.0,4.0,AUTOMATED_MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Convertible,34,24,113,63900
Aston Martin,DB7,2003,premium unleaded (required),420.0,12.0,AUTOMATIC,rear wheel drive,2.0,"Exotic,Factory Tuner,High-Performance",Compact,Coupe,18,11,259,156300
Audi,100,1992,regular unleaded,172.0,6.0,MANUAL,front wheel drive,4.0,Luxury,Midsize,Sedan,24,17,3105,2000
BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
Bentley,Arnage,2007,premium unleaded (required),450.0,8.0,AUTOMATIC,rear wheel drive,4.0,"Exotic,Luxury,Performance",Large,Sedan,15,10,520,221990
Bugatti,Veyron 16.4,2008,premium unleaded (required),1001.0,16.0,AUTOMATED_MANUAL,all wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,14,8,820,2065902
Buick,Cascada,2016,premium unleaded (recommended),200.0,4.0,AUTOMATIC,front wheel drive,2.0,Crossover,Midsize,Convertible,27,20,155,33065
Cadillac,Allante,1991,regular unleaded,200.0,8.0,AUTOMATIC,front wheel drive,2.0,"Luxury,Performance",Compact,Convertible,20,14,1624,2000
Chevrolet,Astro Cargo,2003,regular unleaded,190.0,6.0,AUTOMATIC,rear wheel drive,3.0,"Crossover,Flex Fuel",Large,Cargo Minivan,21,15,1385,22050
Chrysler,200,2015,flex-fuel (unleaded/E85),184.0,4.0,AUTOMATIC,front wheel drive,4.0,Flex Fuel,Midsize,Sedan,36,23,1013,25170
Dodge,Avenger,2012,flex-fuel (unleaded/E85),283.0,6.0,AUTOMATIC,front wheel drive,4.0,"Flex Fuel,Performance",Midsize,Sedan,29,19,1851,25995
FIAT,124 Spider,2017,premium unleaded (recommended),160.0,4.0,MANUAL,rear wheel drive,2.0,Performance,Compact,Convertible,35,26,819,27495
Ferrari,360,2002,premium unleaded (required),400.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,15,10,2774,160829
Ford,Aerostar,1995,regular unleaded,135.0,6.0,AUTOMATIC,rear wheel drive,3.0,Hatchback,Midsize,Cargo Minivan,22,16,5657,2000
GMC,Acadia Limited,2017,regular unleaded,281.0,6.0,AUTOMATIC,front wheel drive,4.0,Crossover,Midsize,4dr SUV,22,15,549,43850
Genesis,G80,2017,regular unleaded,311.0,6.0,AUTOMATIC,rear wheel drive,4.0,"Luxury,Performance",Large,Sedan,28,18,21,41400
HUMMER,H3,2008,regular unleaded,242.0,5.0,MANUAL,four wheel drive,4.0,Luxury,Midsize,4dr SUV,18,13,130,39290
Honda,Accord Crosstour,2010,regular unleaded,271.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback",Midsize,4dr Hatchback,25,17,2202,34020
Hyundai,Accent,2014,regular unleaded,138.0,4.0,AUTOMATIC,front wheel drive,4.0,Hatchback,Compact,4dr Hatchback,37,27,1439,17395
Infiniti,EX35,2008,premium unleaded (recommended),297.0,6.0,AUTOMATIC,rear wheel drive,4.0,"Crossover,Luxury",Midsize,4dr SUV,24,17,190,31900
Kia,Amanti,2007,regular unleaded,264.0,6.0,AUTOMATIC,front wheel drive,4.0,Performance,Midsize,Sedan,24,17,1720,25495
Lamborghini,Aventador,2014,premium unleaded (required),700.0,12.0,AUTOMATED_MANUAL,all wheel drive,2.0,"Exotic,High-Performance",Midsize,Convertible,16,10,1158,441600
Land Rover,Defender,1994,regular unleaded,182.0,8.0,MANUAL,four wheel drive,2.0,Luxury,Compact,2dr SUV,15,12,258,27736
Lexus,CT 200h,2015,regular unleaded,134.0,4.0,AUTOMATIC,front wheel drive,4.0,"Hatchback,Luxury,Hybrid",Compact,4dr Hatchback,40,43,454,32200
Lincoln,Aviator,2003,premium unleaded (required),302.0,8.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,4dr SUV,17,12,61,45125
Lotus,Elise,2009,premium unleaded (required),189.0,4.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Convertible,27,21,613,43995
Maserati,Coupe,2004,premium unleaded (required),390.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,Luxury,High-Performance",Compact,Coupe,15,10,238,81013
Maybach,57,2010,premium unleaded (required),543.0,12.0,AUTOMATIC,rear wheel drive,4.0,"Exotic,Luxury",Large,Sedan,16,10,67,366000
Mazda,2,2012,regular unleaded,100.0,4.0,MANUAL,front wheel drive,4.0,Hatchback,Compact,4dr Hatchback,35,29,586,16020
McLaren,570S,2016,premium unleaded (required),562.0,8.0,AUTOMATED_MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,23,16,416,184900
Mercedes-Benz,190-Class,1991,regular unleaded,130.0,4.0,MANUAL,rear wheel drive,4.0,Luxury,Compact,Sedan,26,18,617,2000
Mitsubishi,3000GT,1997,regular unleaded,218.0,6.0,MANUAL,front wheel drive,2.0,"Hatchback,Performance",Compact,2dr Hatchback,23,17,436,3941
Nissan,200SX,1996,regular unleaded,115.0,4.0,MANUAL,front wheel drive,2.0,Performance,Compact,Coupe,36,26,2009,2000
Oldsmobile,Achieva,1996,regular unleaded,150.0,4.0,MANUAL,front wheel drive,4.0,Performance,Midsize,Sedan,30,20,26,2000
Plymouth,Acclaim,1993,regular unleaded,100.0,4.0,MANUAL,front wheel drive,4.0,Hatchback,Compact,Sedan,29,22,535,2000
Pontiac,6000,1990,regular unleaded,140.0,6.0,AUTOMATIC,front wheel drive,4.0,Crossover,Midsize,Sedan,27,17,210,2000
Porsche,718 Cayman,2017,premium unleaded (required),300.0,4.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,21,1715,53900
Rolls-Royce,Corniche,2001,premium unleaded (required),325.0,8.0,AUTOMATIC,rear wheel drive,2.0,"Exotic,Luxury",Large,Convertible,15,10,86,359990
Saab,9-2X,2005,premium unleaded (required),227.0,4.0,MANUAL,all wheel drive,4.0,"Luxury,Performance",Compact,Wagon,24,17,376,26950
Scion,FR-S,2014,premium unleaded (required),200.0,4.0,MANUAL,rear wheel drive,2.0,Performance,Compact,Coupe,30,22,105,24700
Spyker,C8,2009,premium unleaded (required),400.0,8.0,MANUAL,rear wheel drive,2.0,"Exotic,High-Performance",Compact,Coupe,18,13,2,209990
Subaru,B9 Tribeca,2006,premium unleaded (required),250.0,6.0,AUTOMATIC,all wheel drive,4.0,Crossover,Midsize,4dr SUV,21,16,640,30695
Suzuki,Aerio,2005,regular unleaded,155.0,4.0,AUTOMATIC,all wheel drive,4.0,Crossover,Compact,Sedan,26,21,481,17049
Tesla,Model S,2014,electric,NaN,0.0,DIRECT_DRIVE,rear wheel drive,4.0,"Exotic,High-Performance",Large,Sedan,90,88,1391,79900
Toyota,4Runner,2014,regular unleaded,270.0,6.0,AUTOMATIC,rear wheel drive,4.0,Performance,Midsize,4dr SUV,23,17,2031,41365
Volkswagen,Beetle Convertible,2014,regular unleaded,170.0,4.0,AUTOMATIC,front wheel drive,2.0,Performance,Compact,Convertible,32,24,873,27295
Volvo,240,1991,regular unleaded,114.0,4.0,MANUAL,rear wheel drive,4.0,Luxury,Midsize,Wagon,26,19,870,2000

In [59]:
df.nunique()

Make                   48
Model                 915
Year                   28
Engine Fuel Type       10
Engine HP             356
Engine Cylinders        9
Transmission Type       5
Driven_Wheels           4
Number of Doors         3
Market Category        71
Vehicle Size            3
Vehicle Style          16
highway MPG            59
city mpg               69
Popularity             48
MSRP                 6049
dtype: int64

In [66]:
df.nunique(axis=1)

0        16
1        16
2        16
3        16
4        16
         ..
11909    16
11910    16
11911    16
11912    16
11913    16
Length: 11914, dtype: int64

In [69]:
df.groupby('Make').nunique()

,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
Make,,,,,,,,,,,,,,,
Acura,18,22,3,27,3,3,4,2,12,2,6,17,13,1,208
Alfa Romeo,1,2,1,1,1,1,1,1,1,1,2,1,1,1,5
Aston Martin,12,11,1,13,2,3,1,2,2,3,3,7,6,1,86
Audi,34,20,5,40,6,3,2,2,15,3,6,23,18,1,234
BMW,39,18,5,37,5,4,3,2,17,3,7,27,22,1,263
Bentley,18,12,2,16,2,1,2,2,7,2,3,10,7,1,61
Bugatti,1,2,1,1,1,1,1,1,1,1,1,1,1,1,3
Buick,20,19,4,29,3,1,3,2,10,3,6,17,14,1,156
Cadillac,30,25,5,32,3,2,4,2,11,3,6,16,11,1,319
Chevrolet,63,27,7,68,6,3,4,3,13,3,16,32,27,1,934
Chrysler,19,23,3,27,3,3,4,2,9,3,7,15,11,1,153
Dodge,33,27,4,58,4,3,4,3,13,3,15,26,18,1,366
FIAT,5,3,3,4,2,3,3,2,5,1,4,9,9,1,53
Ferrari,14,14,1,16,2,3,2,1,2,3,2,7,7,1,55
Ford,51,28,5,70,5,4,4,3,20,3,15,30,24,1,684
GMC,30,26,3,30,4,3,4,3,9,3,9,18,13,1,446
Genesis,1,1,2,2,2,1,2,1,2,1,1,3,3,1,3
HUMMER,2,3,2,3,2,2,1,1,4,2,2,2,2,1,15
Honda,21,20,5,31,3,3,4,2,9,3,8,28,26,1,395
Hyundai,22,19,2,40,3,3,3,3,10,3,6,22,20,1,179
Infiniti,38,25,3,33,3,2,4,2,12,3,4,19,17,1,229
Kia,16,10,3,29,4,4,4,2,7,3,6,23,19,1,187
Lamborghini,6,9,1,12,2,2,2,1,2,2,2,8,8,1,34
Land Rover,11,16,5,11,3,2,2,2,10,3,3,12,10,1,118
Lexus,46,24,3,41,4,3,4,2,12,3,6,22,23,1,180
Lincoln,16,21,4,20,3,1,4,2,6,3,5,20,12,1,129
Lotus,5,9,2,9,3,1,1,1,1,1,2,4,5,1,23
Maserati,8,8,1,10,2,3,2,2,4,3,4,11,8,1,45
Maybach,3,3,1,4,1,1,1,1,3,1,2,1,1,1,16
Mazda,31,26,4,44,2,2,4,2,10,3,11,25,18,1,329
McLaren,4,4,1,4,1,1,1,1,1,1,2,2,2,1,5
Mercedes-Benz,40,21,5,56,6,4,4,3,16,3,8,26,20,1,304
Mitsubishi,22,25,4,30,4,4,4,3,7,2,10,26,21,1,140
Nissan,32,20,4,40,4,4,4,3,12,3,13,25,24,1,426
Oldsmobile,18,15,2,18,3,3,3,2,1,3,6,12,10,1,67
Plymouth,10,9,3,12,2,2,3,3,5,3,7,15,13,1,16
Pontiac,20,19,4,39,3,3,3,3,10,3,8,19,15,1,136
Porsche,12,12,3,29,4,3,2,2,9,3,5,12,10,1,97
Rolls-Royce,10,7,1,5,2,1,1,2,3,1,3,4,4,1,31
Saab,8,11,4,19,3,2,2,2,7,3,6,14,10,1,69
Scion,8,8,2,9,1,2,2,2,2,1,5,10,8,1,53
Spyker,1,1,1,1,1,1,1,1,1,1,2,1,1,1,2
Subaru,16,17,3,21,3,2,4,2,7,2,7,18,16,1,144
Suzuki,16,21,1,17,2,2,4,2,3,2,9,17,15,1,216
Tesla,1,3,1,0,1,1,2,1,2,1,1,10,11,1,16
Toyota,39,22,5,43,4,4,4,3,10,3,11,30,30,1,585
Volkswagen,31,23,6,27,6,4,4,3,16,3,8,33,21,1,440
Volvo,26,24,3,22,3,2,3,2,9,3,6,18,12,1,170

In [70]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [71]:
ec=df.loc[:,"Engine Cylinders"]

In [72]:
ec

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ...
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [92]:
d=(ec.fillna(4.0))
d

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ...
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [74]:
M=ec.mode()
M

0    4.0
Name: Engine Cylinders, dtype: float64

In [76]:
x=ec.mean()
x

5.628828677213059

In [91]:
d.median()

6.0

In [99]:
df.Make.index

RangeIndex(start=0, stop=11914, step=1)

In [106]:
df.columns

Index(['Make', 'Model', 'Year', 'Engine Fuel Type', 'Engine HP',
       'Engine Cylinders', 'Transmission Type', 'Driven_Wheels',
       'Number of Doors', 'Market Category', 'Vehicle Size', 'Vehicle Style',
       'highway MPG', 'city mpg', 'Popularity', 'MSRP'],
      dtype='object')

In [118]:
df[['Engine HP','Engine Cylinders']]

       Engine HP  Engine Cylinders
0          335.0               6.0
1          300.0               6.0
2          300.0               6.0
3          230.0               6.0
4          230.0               6.0
...          ...               ...
11909      300.0               6.0
11910      300.0               6.0
11911      300.0               6.0
11912      300.0               6.0
11913      221.0               6.0

[11914 rows x 2 columns]